// Generated by PicoPixel.io — https://picopixel.io
#include "images.h"

#include "src/ui/images/day_clear.inc"
#include "src/ui/images/alert.inc"
const ext_img_desc_t images[2] = {
    { "day_clear", &day_clear },
    { "alert", &alert }
};
