// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;
uint32_t active_theme_index = 0;

void create_screen_uiscreenwarnungpollen() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.uiscreenwarnungpollen = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 320, 240);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(0xffd67a28), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelpollenwarntitel
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelpollenwarntitel = obj;
            lv_obj_set_pos(obj, 27, 86);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c7a, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Pollenwarnung !");
        }
        {
            // labelpollenwarnart
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelpollenwarnart = obj;
            lv_obj_set_pos(obj, 152, 145);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c79, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "--");
        }
        {
            // image_1
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.image_1 = obj;
            lv_obj_set_pos(obj, 120, 5);
            lv_obj_set_size(obj, 81, 81);
            lv_img_set_src(obj, &alert);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_zoom(obj, 81);
            lv_img_set_antialias(obj, true);
        }
        {
            // labelpollenwarnhint
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelpollenwarnhint = obj;
            lv_obj_set_pos(obj, 67, 194);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Tippen zum Bestätigen");
        }
    }

    tick_screen_uiscreenwarnungpollen();
}

void tick_screen_uiscreenwarnungpollen() {
}


void create_screen_screenboot() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screenboot = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 320, 240);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // barwifi
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.barwifi = obj;
            lv_obj_set_pos(obj, 60, 172);
            lv_obj_set_size(obj, 200, 20);
            lv_bar_set_range(obj, 0, 100);
            lv_bar_set_value(obj, 50, LV_ANIM_OFF);
        }
        {
            // labelcuboid
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelcuboid = obj;
            lv_obj_set_pos(obj, 151, 27);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c7a, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xff87ceeb), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Cuboid");
        }
        {
            // labelstatus
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelstatus = obj;
            lv_obj_set_pos(obj, 73, 136);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Verbinde mit WLAN...");
        }
        {
            // labelauthor
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelauthor = obj;
            lv_obj_set_pos(obj, 79, 74);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c79, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "by Jan Althaus");
        }
        {
            // unnamed
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.unnamed = obj;
            lv_obj_set_pos(obj, 49, 27);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c7a, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Pollen");
        }
    }

    tick_screen_screenboot();
}

void tick_screen_screenboot() {
}


void create_screen_screen_1() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_1 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 320, 240);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelgraeserwert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelgraeserwert = obj;
            lv_obj_set_pos(obj, 73, 139);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "gering");
        }
        {
            // labelnameerle
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameerle = obj;
            lv_obj_set_pos(obj, 7, 176);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Erle");
        }
        {
            // imagewetter
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.imagewetter = obj;
            lv_obj_set_pos(obj, 23, 22);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &day_clear);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // labelbirkewert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbirkewert = obj;
            lv_obj_set_pos(obj, 73, 104);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "extrem");
        }
        {
            // labelambrosiawert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelambrosiawert = obj;
            lv_obj_set_pos(obj, 244, 104);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "extrem");
        }
        {
            // labelnamegraeser
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamegraeser = obj;
            lv_obj_set_pos(obj, 7, 139);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Gräser");
        }
        {
            // labelroggenwert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelroggenwert = obj;
            lv_obj_set_pos(obj, 244, 209);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "gering");
        }
        {
            // labeltime
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeltime = obj;
            lv_obj_set_pos(obj, 104, 14);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c7b, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12:45");
        }
        {
            // labelnameesche_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameesche_1 = obj;
            lv_obj_set_pos(obj, 154, 174);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Esche");
        }
        {
            // labelnameroggen_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameroggen_1 = obj;
            lv_obj_set_pos(obj, 154, 209);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Roggen");
        }
        {
            // labelerlewert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelerlewert = obj;
            lv_obj_set_pos(obj, 73, 174);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "--");
        }
        {
            // labelnamebeifuss
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamebeifuss = obj;
            lv_obj_set_pos(obj, 7, 209);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Beifuss");
        }
        {
            // labelhaselwert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelhaselwert = obj;
            lv_obj_set_pos(obj, 244, 139);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "hoch");
        }
        {
            // labelnameambrosia_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameambrosia_1 = obj;
            lv_obj_set_pos(obj, 154, 104);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Ambrosia");
        }
        {
            // labeleschewert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeleschewert = obj;
            lv_obj_set_pos(obj, 244, 174);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "mega");
        }
        {
            // labelbeifusswert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbeifusswert = obj;
            lv_obj_set_pos(obj, 73, 209);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "gering");
        }
        {
            // labelnamehasel
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamehasel = obj;
            lv_obj_set_pos(obj, 154, 139);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Hasel");
        }
        {
            // labelnamebirke_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamebirke_1 = obj;
            lv_obj_set_pos(obj, 7, 103);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c78, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Birke");
        }
        {
            // labeltemp
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeltemp = obj;
            lv_obj_set_pos(obj, 247, 28);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_724e1ec1161c8007800826026d494c79, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "22°C");
        }
    }

    tick_screen_screen_1();
}

void tick_screen_screen_1() {
}


void create_screen_screenforecast2() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screenforecast2 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 320, 240);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelnameesche
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameesche = obj;
            lv_obj_set_pos(obj, 6, 141);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Esche");
        }
        {
            // labelambrosiaday3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelambrosiaday3 = obj;
            lv_obj_set_pos(obj, 237, 38);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "sehr hoch");
        }
        {
            // labelhaselday3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelhaselday3 = obj;
            lv_obj_set_pos(obj, 237, 87);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "hoch");
        }
        {
            // labelday3_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelday3_1 = obj;
            lv_obj_set_pos(obj, 222, 7);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Übermorgen");
        }
        {
            // labelday2
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelday2 = obj;
            lv_obj_set_pos(obj, 158, 7);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Morgen");
        }
        {
            // labelnameroggen
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameroggen = obj;
            lv_obj_set_pos(obj, 4, 194);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Roggen");
        }
        {
            // labelnameambrosia
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameambrosia = obj;
            lv_obj_set_pos(obj, 6, 38);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Ambrosia");
        }
        {
            // labelroggenday1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelroggenday1 = obj;
            lv_obj_set_pos(obj, 82, 194);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "--");
        }
        {
            // label_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.label_1 = obj;
            lv_obj_set_pos(obj, 82, 7);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Heute");
        }
        {
            // labelroggenday3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelroggenday3 = obj;
            lv_obj_set_pos(obj, 237, 194);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "sehr hoch");
        }
        {
            // labelambrosiaday2
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelambrosiaday2 = obj;
            lv_obj_set_pos(obj, 158, 38);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "mittel");
        }
        {
            // labelhaselday2
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelhaselday2 = obj;
            lv_obj_set_pos(obj, 158, 85);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "mittel");
        }
        {
            // labelhaselday1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelhaselday1 = obj;
            lv_obj_set_pos(obj, 82, 85);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "gering");
        }
        {
            // labelescheday1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelescheday1 = obj;
            lv_obj_set_pos(obj, 82, 141);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "--");
        }
        {
            // labelescheday3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelescheday3 = obj;
            lv_obj_set_pos(obj, 237, 141);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "gering");
        }
        {
            // labelambrosiaday1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelambrosiaday1 = obj;
            lv_obj_set_pos(obj, 82, 38);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "stark");
        }
        {
            // labelnamehasel_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamehasel_1 = obj;
            lv_obj_set_pos(obj, 6, 88);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Hasel");
        }
        {
            // labelescheday2
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelescheday2 = obj;
            lv_obj_set_pos(obj, 158, 141);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_x(obj, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_y(obj, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_angle(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "keine");
        }
        {
            // labelroggenday2
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelroggenday2 = obj;
            lv_obj_set_pos(obj, 158, 194);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "hoch");
        }
    }

    tick_screen_screenforecast2();
}

void tick_screen_screenforecast2() {
}


void create_screen_screenforecast() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screenforecast = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 320, 240);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelday3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelday3 = obj;
            lv_obj_set_pos(obj, 222, 7);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Übermorgen");
        }
        {
            // labelgraeserday1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelgraeserday1 = obj;
            lv_obj_set_pos(obj, 82, 87);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "--");
        }
        {
            // labelbeifussday1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbeifussday1 = obj;
            lv_obj_set_pos(obj, 82, 194);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "mittel");
        }
        {
            // labelbirkeday1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbirkeday1 = obj;
            lv_obj_set_pos(obj, 82, 38);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "stark");
        }
        {
            // labelday1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelday1 = obj;
            lv_obj_set_pos(obj, 82, 7);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Heute");
        }
        {
            // labelgraeserday3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelgraeserday3 = obj;
            lv_obj_set_pos(obj, 237, 88);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "--");
        }
        {
            // labelerleday2
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelerleday2 = obj;
            lv_obj_set_pos(obj, 158, 141);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "--");
        }
        {
            // labelnamebirke
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamebirke = obj;
            lv_obj_set_pos(obj, 6, 38);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Birke");
        }
        {
            // labelbirkeday2
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbirkeday2 = obj;
            lv_obj_set_pos(obj, 158, 37);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "stark");
        }
        {
            // labelgraeserday2
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelgraeserday2 = obj;
            lv_obj_set_pos(obj, 158, 88);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "mittel");
        }
        {
            // labelnamegraeser_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamegraeser_1 = obj;
            lv_obj_set_pos(obj, 6, 88);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Gräser");
        }
        {
            // labelnamebeifuss_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamebeifuss_1 = obj;
            lv_obj_set_pos(obj, 6, 194);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Beifuss");
        }
        {
            // labelday2_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelday2_1 = obj;
            lv_obj_set_pos(obj, 156, 7);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Morgen");
        }
        {
            // labelerleday3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelerleday3 = obj;
            lv_obj_set_pos(obj, 237, 141);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "--");
        }
        {
            // labelnameerle_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameerle_1 = obj;
            lv_obj_set_pos(obj, 6, 141);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Erle");
        }
        {
            // labelbirkeday3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbirkeday3 = obj;
            lv_obj_set_pos(obj, 237, 37);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "gering");
        }
        {
            // labelerleday1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelerleday1 = obj;
            lv_obj_set_pos(obj, 82, 141);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "hoch");
        }
        {
            // labelbeifussday3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbeifussday3 = obj;
            lv_obj_set_pos(obj, 237, 194);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "hoch");
        }
        {
            // labelbeifussday2
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbeifussday2 = obj;
            lv_obj_set_pos(obj, 158, 194);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_0717f753465d8037800829e0a27bf73d, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "--");
        }
    }

    tick_screen_screenforecast();
}

void tick_screen_screenforecast() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_uiscreenwarnungpollen,
    tick_screen_screenboot,
    tick_screen_screen_1,
    tick_screen_screenforecast2,
    tick_screen_screenforecast,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_uiscreenwarnungpollen() {
    if (objects.uiscreenwarnungpollen != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.uiscreenwarnungpollen);
        lv_obj_del(objects.uiscreenwarnungpollen);
    }
    objects.uiscreenwarnungpollen = 0;
    objects.labelpollenwarntitel = 0;
    objects.labelpollenwarnart = 0;
    objects.image_1 = 0;
    objects.labelpollenwarnhint = 0;
}

void delete_screen_screenboot() {
    if (objects.screenboot != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screenboot);
        lv_obj_del(objects.screenboot);
    }
    objects.screenboot = 0;
    objects.barwifi = 0;
    objects.labelcuboid = 0;
    objects.labelstatus = 0;
    objects.labelauthor = 0;
    objects.unnamed = 0;
}

void delete_screen_screen_1() {
    if (objects.screen_1 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_1);
        lv_obj_del(objects.screen_1);
    }
    objects.screen_1 = 0;
    objects.labelgraeserwert = 0;
    objects.labelnameerle = 0;
    objects.imagewetter = 0;
    objects.labelbirkewert = 0;
    objects.labelambrosiawert = 0;
    objects.labelnamegraeser = 0;
    objects.labelroggenwert = 0;
    objects.labeltime = 0;
    objects.labelnameesche_1 = 0;
    objects.labelnameroggen_1 = 0;
    objects.labelerlewert = 0;
    objects.labelnamebeifuss = 0;
    objects.labelhaselwert = 0;
    objects.labelnameambrosia_1 = 0;
    objects.labeleschewert = 0;
    objects.labelbeifusswert = 0;
    objects.labelnamehasel = 0;
    objects.labelnamebirke_1 = 0;
    objects.labeltemp = 0;
}

void delete_screen_screenforecast2() {
    if (objects.screenforecast2 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screenforecast2);
        lv_obj_del(objects.screenforecast2);
    }
    objects.screenforecast2 = 0;
    objects.labelnameesche = 0;
    objects.labelambrosiaday3 = 0;
    objects.labelhaselday3 = 0;
    objects.labelday3_1 = 0;
    objects.labelday2 = 0;
    objects.labelnameroggen = 0;
    objects.labelnameambrosia = 0;
    objects.labelroggenday1 = 0;
    objects.label_1 = 0;
    objects.labelroggenday3 = 0;
    objects.labelambrosiaday2 = 0;
    objects.labelhaselday2 = 0;
    objects.labelhaselday1 = 0;
    objects.labelescheday1 = 0;
    objects.labelescheday3 = 0;
    objects.labelambrosiaday1 = 0;
    objects.labelnamehasel_1 = 0;
    objects.labelescheday2 = 0;
    objects.labelroggenday2 = 0;
}

void delete_screen_screenforecast() {
    if (objects.screenforecast != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screenforecast);
        lv_obj_del(objects.screenforecast);
    }
    objects.screenforecast = 0;
    objects.labelday3 = 0;
    objects.labelgraeserday1 = 0;
    objects.labelbeifussday1 = 0;
    objects.labelbirkeday1 = 0;
    objects.labelday1 = 0;
    objects.labelgraeserday3 = 0;
    objects.labelerleday2 = 0;
    objects.labelnamebirke = 0;
    objects.labelbirkeday2 = 0;
    objects.labelgraeserday2 = 0;
    objects.labelnamegraeser_1 = 0;
    objects.labelnamebeifuss_1 = 0;
    objects.labelday2_1 = 0;
    objects.labelerleday3 = 0;
    objects.labelnameerle_1 = 0;
    objects.labelbirkeday3 = 0;
    objects.labelerleday1 = 0;
    objects.labelbeifussday3 = 0;
    objects.labelbeifussday2 = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_uiscreenwarnungpollen,
    delete_screen_screenboot,
    delete_screen_screen_1,
    delete_screen_screenforecast2,
    delete_screen_screenforecast,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_uiscreenwarnungpollen();
    create_screen_screenboot();
    create_screen_screen_1();
    create_screen_screenforecast2();
    create_screen_screenforecast();
}
