// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *uiscreenwarnungpollen;
    lv_obj_t *screenboot;
    lv_obj_t *screen_1;
    lv_obj_t *labelgraeserwert;
    lv_obj_t *labelnameerle;
    lv_obj_t *labelpollenwarntitel;
    lv_obj_t *imagewetter;
    lv_obj_t *labelpollenwarnart;
    lv_obj_t *labelbirkewert;
    lv_obj_t *labelambrosiawert;
    lv_obj_t *labelnamegraeser;
    lv_obj_t *barwifi;
    lv_obj_t *labelroggenwert;
    lv_obj_t *image_1;
    lv_obj_t *labeltime;
    lv_obj_t *labelnameesche;
    lv_obj_t *labelnameroggen;
    lv_obj_t *labelerlewert;
    lv_obj_t *labelnamebeifuss;
    lv_obj_t *labelcuboid;
    lv_obj_t *labelhaselwert;
    lv_obj_t *labelnameambrosia;
    lv_obj_t *labeleschewert;
    lv_obj_t *labelstatus;
    lv_obj_t *labelbeifusswert;
    lv_obj_t *labelnamehasel;
    lv_obj_t *labelnamebirke;
    lv_obj_t *labelauthor;
    lv_obj_t *labelpollenwarnhint;
    lv_obj_t *labeltemp;
    lv_obj_t *unnamed;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_UISCREENWARNUNGPOLLEN = 1,
    SCREEN_ID_SCREENBOOT = 2,
    SCREEN_ID_SCREEN_1 = 3,
};

void create_screen_uiscreenwarnungpollen();
void tick_screen_uiscreenwarnungpollen();
void delete_screen_uiscreenwarnungpollen();
void create_screen_screenboot();
void tick_screen_screenboot();
void delete_screen_screenboot();
void create_screen_screen_1();
void tick_screen_screen_1();
void delete_screen_screen_1();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
