// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_FONTS_H
#define PICOPIXEL_LVGL_UI_FONTS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Custom font declarations (externally visible const structs, no init needed) */
extern const lv_font_t font_724e1ec1161c8007800826026d494c78;
extern const lv_font_t font_724e1ec1161c8007800826026d494c79;
extern const lv_font_t font_724e1ec1161c8007800826026d494c7a;
extern const lv_font_t font_724e1ec1161c8007800826026d494c7b;

/* Get a custom font by name, returns NULL if not found */
const lv_font_t* ui_get_font_by_name(const char* name);

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_FONTS_H*/
