#!/bin/bash
# apply_picopixel_export.sh
#
# Wendet alle nötigen Korrekturen auf einen frischen PicoPixel-Export an.
#
# Verwendung:
#   ./tools/apply_picopixel_export.sh <export-ordner>
#
# Beispiel:
#   ./tools/apply_picopixel_export.sh ~/Downloads/lvgl_ui
#
# Das Script:
#   1. Kopiert den Export nach src/ui/ (überschreibt bestehende Dateien)
#   2. Benennt Bilddateien .c → .inc um
#   3. Fixiert lvgl/lvgl.h → <lvgl.h> in allen Font-Dateien
#   4. Fixiert images.c (Pfade + Wetter-Icons hinzufügen)
#   5. Fixiert images.h (Wetter-Icon-Deklarationen + Array-Größe)
#   6. Fixiert ui.c (loadScreenNow hinzufügen, loadScreen aus ui_init entfernen)
#   7. Fixiert ui.h (loadScreenNow deklarieren)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
UI_DIR="$PROJECT_DIR/src/ui"
WETTERCUBE_DIR="/Users/janalthaus/Documents/Arduino/wettercube"

# ── Argumente prüfen ─────────────────────────────────────────────────────────
if [ -z "$1" ]; then
    echo "Fehler: Kein Export-Ordner angegeben."
    echo "Verwendung: $0 <export-ordner>"
    exit 1
fi

EXPORT_DIR="$1"
if [ ! -d "$EXPORT_DIR" ]; then
    echo "Fehler: Ordner nicht gefunden: $EXPORT_DIR"
    exit 1
fi

echo "==> Pollencuboid PicoPixel Export Patcher"
echo "    Export:  $EXPORT_DIR"
echo "    Ziel:    $UI_DIR"
echo ""

# ── 1. Export nach src/ui/ kopieren ──────────────────────────────────────────
echo "[1/7] Kopiere Export nach src/ui/ ..."
# Nur die generierten Dateien übernehmen, nicht unsere eigenen Tools
cp -r "$EXPORT_DIR/src/ui/." "$UI_DIR/"
# Falls Export flach ist (ohne src/ui Unterstruktur), direkt kopieren
if [ ! -f "$UI_DIR/screens.h" ] && [ -f "$EXPORT_DIR/screens.h" ]; then
    cp "$EXPORT_DIR"/*.c "$EXPORT_DIR"/*.h "$UI_DIR/" 2>/dev/null || true
fi
echo "    OK"

# ── 2. Bilddateien .c → .inc umbenennen ──────────────────────────────────────
echo "[2/7] Benenne Bilddateien .c → .inc um ..."
for f in "$UI_DIR/images/"*.c; do
    [ -f "$f" ] || continue
    base=$(basename "$f" .c)
    mv "$f" "$UI_DIR/images/${base}.inc"
    echo "    $base.c → $base.inc"
done

# ── 3. lvgl/lvgl.h → <lvgl.h> in Font-Dateien ───────────────────────────────
echo "[3/7] Fixiere lvgl-Include in Font-Dateien ..."
for f in "$UI_DIR/fonts/"*.c; do
    [ -f "$f" ] || continue
    sed -i '' 's|#include "lvgl/lvgl.h"|#include <lvgl.h>|g' "$f"
done
echo "    OK"

# ── 4. Wetter-Icons aus WetterCube kopieren (falls nicht vorhanden) ───────────
echo "[4/7] Stelle Wetter-Icons sicher ..."
for icon in overcast fog rain snow thunder; do
    dest="$UI_DIR/images/${icon}.inc"
    if [ ! -f "$dest" ]; then
        src="$WETTERCUBE_DIR/ui_img_${icon}_png.c"
        if [ ! -f "$src" ]; then
            echo "    WARNUNG: $src nicht gefunden — Icon übersprungen"
            continue
        fi
        cp "$src" "$dest"
        sed -i '' '/#include "ui.h"/d' "$dest"
        echo "    $icon.inc kopiert"
    else
        echo "    $icon.inc bereits vorhanden"
    fi
done

# ── 5. images.c neu schreiben ─────────────────────────────────────────────────
echo "[5/7] Schreibe images.c ..."
cat > "$UI_DIR/images.c" << 'EOF'
// Generated by PicoPixel.io — https://picopixel.io
#include "images.h"

#include "src/ui/images/day_clear.inc"
#include "src/ui/images/alert.inc"
#include "src/ui/images/overcast.inc"
#include "src/ui/images/fog.inc"
#include "src/ui/images/rain.inc"
#include "src/ui/images/snow.inc"
#include "src/ui/images/thunder.inc"
const ext_img_desc_t images[7] = {
    { "day_clear", &day_clear },
    { "alert",     &alert },
    { "overcast",  &ui_img_overcast_png },
    { "fog",       &ui_img_fog_png },
    { "rain",      &ui_img_rain_png },
    { "snow",      &ui_img_snow_png },
    { "thunder",   &ui_img_thunder_png },
};
EOF
echo "    OK"

# ── 6. images.h — Wetter-Icon-Deklarationen einfügen ─────────────────────────
echo "[6/7] Patche images.h ..."
# Ersetze die images[N]-Zeile und füge Icon-Deklarationen ein
python3 - "$UI_DIR/images.h" << 'PYEOF'
import sys, re

path = sys.argv[1]
with open(path) as f:
    content = f.read()

# Entferne alle bereits vorhandenen Wetter-Icon-Deklarationen (idempotent)
content = re.sub(r'extern const lv_img_dsc_t ui_img_\w+;\n', '', content)
# Ersetze images[N] durch images[7]
content = re.sub(r'extern const ext_img_desc_t images\[\d+\];',
                 'extern const ext_img_desc_t images[7];', content)

# Füge Icon-Deklarationen nach "extern const lv_img_dsc_t alert;" ein
insert = (
    'extern const lv_img_dsc_t ui_img_overcast_png;\n'
    'extern const lv_img_dsc_t ui_img_fog_png;\n'
    'extern const lv_img_dsc_t ui_img_rain_png;\n'
    'extern const lv_img_dsc_t ui_img_snow_png;\n'
    'extern const lv_img_dsc_t ui_img_thunder_png;\n'
)
content = content.replace(
    'extern const lv_img_dsc_t alert;\n',
    'extern const lv_img_dsc_t alert;\n' + insert
)

with open(path, 'w') as f:
    f.write(content)
PYEOF
echo "    OK"

# ── 7. ui.c patchen ───────────────────────────────────────────────────────────
echo "[7/7] Patche ui.c und ui.h ..."
python3 - "$UI_DIR/ui.c" << 'PYEOF'
import sys, re

path = sys.argv[1]
with open(path) as f:
    content = f.read()

# loadScreen aus ui_init entfernen
content = re.sub(
    r'(void ui_init\(\) \{)\s*\n\s*create_screens\(\);\s*\n\s*loadScreen\([^)]+\);\s*\n(\})',
    r'\1\n    create_screens();\n    // kein loadScreen hier — setup() übernimmt den ersten Screen\n\2',
    content
)

# loadScreenNow hinzufügen falls nicht vorhanden
if 'loadScreenNow' not in content:
    content = content.replace(
        'void ui_init() {',
        'void loadScreenNow(enum ScreensEnum screenId) {\n'
        '    currentScreen = screenId - 1;\n'
        '    lv_obj_t *screen = getLvglObjectFromIndex(currentScreen);\n'
        '    lv_scr_load(screen);\n'
        '}\n\n'
        'void ui_init() {'
    )

with open(path, 'w') as f:
    f.write(content)
PYEOF

# ui.h: loadScreenNow deklarieren falls nicht vorhanden
if ! grep -q "loadScreenNow" "$UI_DIR/ui.h"; then
    sed -i '' 's|void loadScreen(enum ScreensEnum screenId);|void loadScreen(enum ScreensEnum screenId);\nvoid loadScreenNow(enum ScreensEnum screenId);|' "$UI_DIR/ui.h"
fi
echo "    OK"

echo ""
echo "✓ Alle Fixes angewendet. Bereit zum Kompilieren."
